# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20171021_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('last_evaluation', models.DecimalField(decimal_places=2, max_digits=3)),
                ('number_project', models.IntegerField()),
                ('average_montly_hours', models.IntegerField()),
                ('time_spend_company', models.IntegerField()),
                ('Work_accident', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')])),
                ('left', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')])),
                ('promotion_last_5years', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')])),
                ('department', models.IntegerField(choices=[(0, 'sales'), (1, 'accounting'), (2, 'hr'), (3, 'technical'), (4, 'support'), (5, 'management'), (6, 'IT'), (7, 'product_mng'), (8, 'marketing'), (9, 'RandD')])),
                ('salary', models.IntegerField(choices=[(0, 'LOW'), (1, 'MEDIUM'), (2, 'HIGH')])),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
