# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_empreview_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreview',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
