# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_emppossibleresigneereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='users',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
