# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20171111_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='wine',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Wine',
        ),
    ]
